### ISSUE TITLE
React Scripts need to be updated to 3.4.1

### ISSUE THREAD

**Issue by l0609890** [alochaus/react-blog#8]
There has been this wierd bugs when people use `npm audit fix` that causes the react application to crash. You can read more of it here : 

https://stackoverflow.com/questions/60234640/typeerror-err-invalid-arg-type-the-path-argument-must-be-of-type-string-re/62287792#62287792 . 

I notice this same bug pop up in the app , because the react-script was 3.3.0 .

**Comment by alochaus** [comment]
Thanks for letting me know.
